services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
      - MERCADOPAGO_PUBLIC_KEY=${MERCADOPAGO_PUBLIC_KEY}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_CREDENTIALS_PATH=${GCP_CREDENTIALS_PATH}
    volumes:
      - ./backend:/app
      - ./mnd-midias-2c0bfa9a103c.json:/app/mnd-midias-2c0bfa9a103c.json:ro
    depends_on:
      - db

  frontend-admin:
    build: ./frontend-admin
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_KEY}
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules

  frontend-user:
    build: ./frontend-user
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_KEY}
    volumes:
      - ./frontend-user:/app
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ticketmetal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
